### ISSUE TITLE
FriendlyId support (again)

### ISSUE THREAD

**Issue by coorasse** [CanCanCommunity/cancancan#106]
Looking through all the possible solutions for the FriendlyId integration I found a possible solution that fits perfectly my project and looks pretty cool because you do not have to change anything in controllers or model and it works just out of the box.
You do not have to write `find_by :slug` or something like that, that is always error prone.

You just need to create a `config/initizializers/cancan.rb` file with:

``` ruby
if defined?(CanCan)
  class Object
    def metaclass
      class << self; self; end
    end
  end

  module CanCan
    module ModelAdapters
      class ActiveRecord4Adapter < AbstractAdapter
        @@friendly_support = {}

        def self.find(model_class, id)
          klass =
          model_class.metaclass.ancestors.include?(ActiveRecord::Associations::CollectionProxy) ?
            model_class.klass : model_class
          @@friendly_support[klass]||=klass.metaclass.ancestors.include?(FriendlyId)
          @@friendly_support[klass] == true ? model_class.friendly.find(id) : model_class.find(id)
        end
      end
    end
  end
end
```

I actually found this code from @aantix and updated it to works also on Rails4 and associations.
I would like to integrate it into cancancan with an explicit option to activate it or just create a page on the wiki if you agree.

**Comment by evanscottgray** [comment]
After trying out the solution in https://github.com/CanCanCommunity/cancancan/wiki/FriendlyId-support, we were running into the following error:
```
/app/config/initializers/cancan.rb:36:in `<module:ModelAdapters>': superclass mismatch for class ActiveRecord4Adapter (TypeError)
	from /app/config/initializers/cancan.rb:35:in `<module:CanCan>'
	from /app/config/initializers/cancan.rb:34:in `<main>'
	from /usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	from /usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	from /usr/local/bundle/gems/activesupport-6.0.0.rc2/lib/active_support/dependencies.rb:316:in `block in load'
	from /usr/local/bundle/gems/activesupport-6.0.0.rc2/lib/active_support/dependencies.rb:288:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-6.0.0.rc2/lib/active_support/dependencies.rb:316:in `load'
	from /usr/local/bundle/gems/railties-6.0.0.rc2/lib/rails/engine.rb:667:in `block in load_config_initializer'
	from /usr/local/bundle/gems/activesupport-6.0.0.rc2/lib/active_support/notifications.rb:182:in `instrument'
	from /usr/local/bundle/gems/railties-6.0.0.rc2/lib/rails/engine.rb:666:in `load_config_initializer'
	from /usr/local/bundle/gems/railties-6.0.0.rc2/lib/rails/engine.rb:624:in `block (2 levels) in <class:Engine>'
	from /usr/local/bundle/gems/railties-6.0.0.rc2/lib/rails/engine.rb:623:in `each'
	from /usr/local/bundle/gems/railties-6.0.0.rc2/lib/rails/engine.rb:623:in `block in <class:Engine>'
	from /usr/local/bundle/gems/railties-6.0.0.rc2/lib/rails/initializable.rb:32:in `instance_exec'
	from /usr/local/bundle/gems/railties-6.0.0.rc2/lib/rails/initializable.rb:32:in `run'
	from /usr/local/bundle/gems/railties-6.0.0.rc2/lib/rails/initializable.rb:61:in `block in run_initializers'
```

We were able to fix this by adding `require_dependency 'cancan/model_adapters/active_record_4_adapter'` and changing `AbstractAdapter` to `ActiveRecordAdapter` as seen below:
```ruby
require_dependency 'cancan/model_adapters/active_record_4_adapter'

if defined?(CanCan)
  class Object
    def metaclass
      class << self; self; end
    end
  end

  module CanCan
    module ModelAdapters
      class ActiveRecord4Adapter < ActiveRecordAdapter
        @@friendly_support = {}

        def self.find(model_class, id)
          klass =
              model_class.metaclass.ancestors.include?(ActiveRecord::Associations::CollectionProxy) ?
                  model_class.klass : model_class
          @@friendly_support[klass]||=klass.metaclass.ancestors.include?(FriendlyId)
          @@friendly_support[klass] == true ? model_class.friendly.find(id) : model_class.find(id)
        end
      end
    end
  end
end
```
It appears everything is working again. While this may be related to our environment, it is possible the wiki may need an update.

**Comment by ebaudet** [comment]
@evanscottgray No need to require_dependency, if the ActiveRecord used is 4+, you just have to change to :
```ruby
class ActiveRecordAdapter < ActiveRecordAdapter
```
