### ISSUE TITLE
Doesn't load_resource on index only with combination of can & cannot block

### ISSUE THREAD

**Issue by itsmechlark** [CanCanCommunity/cancancan#122]
cancancan doesn't load resource on index only which:

[lib/cancan/controller_resource.rb#L77](https://github.com/CanCanCommunity/cancancan/blob/v1.9.2/lib/cancan/controller_resource.rb#L77)
```
resource_base.respond_to?(:accessible_by) # => true
current_ability.has_block?(authorization_action, resource_class) # => true
```

[lib/cancan/ability.rb#L311](https://github.com/CanCanCommunity/cancancan/blob/v1.9.2/lib/cancan/ability.rb#L311)
```
relevant_rules(action, subject) # => [#<CanCan::Rule:0x007f857c2182a8 @match_all=true, @base_behavior=false, @actions=[nil], @subjects=[nil], @conditions={}, @block=#<Proc:0x007f857c218870@/Users/itsmechlark/Desktop/GitHub/itsmechlark/cms/app/models/ability.rb:23>, @expanded_actions=[nil]>, #<CanCan::Rule:0x007f857c2191a8 @match_all=true, @base_behavior=true, @actions=[nil], @subjects=[nil], @conditions={}, @block=#<Proc:0x007f857c219270@/Users/itsmechlark/Desktop/GitHub/itsmechlark/cms/app/models/ability.rb:17>, @expanded_actions=[nil]>, #<CanCan::Rule:0x007f857c21a2d8 @match_all=false, @base_behavior=true, @actions=[:read, :create, :update], @subjects=[Lda::Section(id: integer, user_id: integer, name: string, ancestry: string, rank: integer, created_at: datetime, updated_at: datetime)], @conditions={}, @block=nil, @expanded_actions=[:read, :index, :show, :create, :new, :update, :edit]>]
```

<b>Fulltrace</b>
undefined method `order' for nil:NilClass
app/controllers/lda/sections_controller.rb#8
```
app/controllers/lda/sections_controller.rb:8:in `index'
actionpack (4.1.4) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.1.4) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.1.4) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.1.4) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.1.4) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.4) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.4) lib/active_support/callbacks.rb:149:in `call'
activesupport (4.1.4) lib/active_support/callbacks.rb:149:in `block in halting_and_conditional'
activesupport (4.1.4) lib/active_support/callbacks.rb:229:in `call'
activesupport (4.1.4) lib/active_support/callbacks.rb:229:in `block in halting'
activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.4) lib/active_support/callbacks.rb:229:in `call'
activesupport (4.1.4) lib/active_support/callbacks.rb:229:in `block in halting'
activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.4) lib/active_support/callbacks.rb:229:in `call'
activesupport (4.1.4) lib/active_support/callbacks.rb:229:in `block in halting'
activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.4) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.4) lib/active_support/callbacks.rb:86:in `call'
activesupport (4.1.4) lib/active_support/callbacks.rb:86:in `run_callbacks'
actionpack (4.1.4) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.1.4) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.1.4) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.1.4) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.1.4) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.1.4) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.1.4) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.1.4) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.1.4) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.1.4) lib/abstract_controller/base.rb:136:in `process'
actionview (4.1.4) lib/action_view/rendering.rb:30:in `process'
actionpack (4.1.4) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.1.4) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.1.4) lib/action_controller/metal.rb:232:in `block in action'
actionpack (4.1.4) lib/action_dispatch/routing/route_set.rb:82:in `call'
actionpack (4.1.4) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
actionpack (4.1.4) lib/action_dispatch/routing/route_set.rb:50:in `call'
actionpack (4.1.4) lib/action_dispatch/journey/router.rb:71:in `block in call'
actionpack (4.1.4) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.1.4) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.1.4) lib/action_dispatch/routing/route_set.rb:678:in `call'
pdfkit (0.6.2) lib/pdfkit/middleware.rb:17:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.5.2) lib/rack/etag.rb:23:in `call'
rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
rack (1.5.2) lib/rack/head.rb:11:in `call'
actionpack (4.1.4) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.1.4) lib/action_dispatch/middleware/flash.rb:254:in `call'
rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.1.4) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.1.4) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.1.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
activerecord (4.1.4) lib/active_record/migration.rb:380:in `call'
actionpack (4.1.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.1.4) lib/active_support/callbacks.rb:82:in `run_callbacks'
actionpack (4.1.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.1.4) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.1.4) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.1.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.1.4) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.1.4) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.1.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.1.4) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.1.4) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.1.4) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.1.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
rack (1.5.2) lib/rack/runtime.rb:17:in `call'
activesupport (4.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
rack (1.5.2) lib/rack/lock.rb:17:in `call'
actionpack (4.1.4) lib/action_dispatch/middleware/static.rb:64:in `call'
rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
railties (4.1.4) lib/rails/engine.rb:514:in `call'
railties (4.1.4) lib/rails/application.rb:144:in `call'
rack (1.5.2) lib/rack/content_length.rb:14:in `call'
thin (1.6.2) lib/thin/connection.rb:86:in `block in pre_process'
thin (1.6.2) lib/thin/connection.rb:84:in `catch'
thin (1.6.2) lib/thin/connection.rb:84:in `pre_process'
thin (1.6.2) lib/thin/connection.rb:53:in `process'
thin (1.6.2) lib/thin/connection.rb:39:in `receive_data'
eventmachine (1.0.3) lib/eventmachine.rb:187:in `run_machine'
eventmachine (1.0.3) lib/eventmachine.rb:187:in `run'
thin (1.6.2) lib/thin/backends/base.rb:73:in `start'
thin (1.6.2) lib/thin/server.rb:162:in `start'
rack (1.5.2) lib/rack/handler/thin.rb:16:in `run'
rack (1.5.2) lib/rack/server.rb:264:in `start'
railties (4.1.4) lib/rails/commands/server.rb:69:in `start'
railties (4.1.4) lib/rails/commands/commands_tasks.rb:81:in `block in server'
railties (4.1.4) lib/rails/commands/commands_tasks.rb:76:in `tap'
railties (4.1.4) lib/rails/commands/commands_tasks.rb:76:in `server'
railties (4.1.4) lib/rails/commands/commands_tasks.rb:40:in `run_command!'
railties (4.1.4) lib/rails/commands.rb:17:in `<top (required)>'
script/rails:6:in `require'
script/rails:6:in `<main>'
```

<b>app/controllers/lda/sections_controller.rb</b>
```
class Lda::SectionsController < LdaController

  load_and_authorize_resource

  # GET /lda/sections
  # GET /lda/sections.json
  def index
    @lda_sections = @lda_sections.order('`lda_sections`.`ancestry` ASC, `lda_sections`.`rank` ASC, `lda_sections`.`name` ASC')
  end

  # GET /lda/sections/new
  def new
    @lda_section.user_id = current_user.id
  end

  # GET /lda/sections/1/edit
  def edit
  end

  # POST /lda/sections
  # POST /lda/sections.json
  def create
    respond_to do |format|
      if @lda_section.save
        format.html { redirect_to @lda_section, notice: 'Section was successfully created.' }
        format.json { render status: :created, json: @lda_section }
        format.js { render status: :created, nothing: true }
      else
        format.html { render action: 'new' }
        format.json { render json: @lda_section.errors, status: :unprocessable_entity }
        format.js { render status: :unprocessable_entity, nothing: true }
      end
    end
  end

  # PATCH/PUT /lda/sections/1
  # PATCH/PUT /lda/sections/1.json
  def update
    respond_to do |format|
      if @lda_section.update(lda_section_params)
        format.html { redirect_to @lda_section, notice: 'Section was successfully updated.' }
        format.json { render status: :ok, json: @lda_section }
        format.js { render status: :ok, nothing: true }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lda_section.errors, status: :unprocessable_entity }
        format.js { render status: :unprocessable_entity, nothing: true }
      end
    end
  end

  # DELETE /lda/sections/1
  # DELETE /lda/sections/1.json
  def destroy
    @lda_section.destroy
    respond_to do |format|
      format.html { redirect_to lda_sections_url }
      format.json {  render status: :ok, nothing: true }
      format.js { render status: :ok, nothing: true }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def resource_params
      params.require(:lda_section).permit(:user_id, :name, :ancestry, :rank)
    end
end

```

<b>app/models/ability.rb</b>
```
class Ability
  include CanCan::Ability

  def initialize(user, *args)
    lda_initialize(user, args)
    global_ability(user, args) # Add special and constraints to ability
  end

  # Load all permission from the database. This will overwrite ability previously declared.
  # It will add constraints if it's a cannot? permissions specified at ability_can == false.
  # Load this in the end of initializing abilities to fully use the constraints.
  #
  # @params [Class] user - an authenticated user
  # @params [Hash] args
  def global_ability(user, *args)
    # Abilities
    can do |action, subject_class, subject|
      user.permissions.where(action: aliases_for_action(action), ability_can: true).any? do |permission|
        permission.subject_class_type == subject_class.to_s && (subject.nil? || permission.subject_class_id.nil? || permission.subject_class_id == subject.id)
      end
    end
    # Constraints
    cannot do |action, subject_class, subject|
      user.permissions.where(action: aliases_for_action(action), ability_can: false).any? do |permission|
        permission.subject_class_type == subject_class.to_s && (subject.nil? || permission.subject_class_id.nil? || permission.subject_class_id == subject.id)
      end
    end
  end

  # Add ability to authenticated user for Lda which inherited from roles.
  #
  # @params [Class] user - an authenticated user
  # @params [Hash] args
  def lda_initialize(user, *args)
    can [:read, :update, :destroy], Lda::Document, # Allow only the author to :read & :update a Lda::Document for privacy :private
        {privacy: {privacy_type: :private},
         lda_document_authors: {author_id: user.profile_id}}
    can :create, Lda::Document if user.has_role?(:lda_author) # Allow author to create a Lda::Document
    can [:read, :create, :update, :destroy], Lda::Document if user.has_role?(:lda_editor, :lda_partner) # Full access to Lda::Document
    can :read, Lda::Document, privacy: {privacy_type: :public} # Allow to :read a Lda::Document for privacy :public
    can [:read, :create, :update], Lda::Section if user.has_role?(:lda_admin) # Allow to :update a Lda::Section if has_role?(:admin)
  end
end
```

ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
rails (4.1.4)
cancancan (1.9.2)

**Comment by bryanrite** [comment]
Closing as this seems to be abandoned. Please reopen if you are still having issues.
