### ISSUE TITLE
"load_and_authorize_resource" throwing ActiveRecord::RecordNotFound for inexistent resource and its "find_by" option doesn't seem helpful either

### ISSUE THREAD

**Issue by jiggneshhgohel** [CanCanCommunity/cancancan#193]
```
Rails 4.2.0
Ruby 2.2.1 [ x86_64 ]
Devise 3.4.1
CanCanCan 1.10.1.
```

**app/models/ability.rb**

```
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # in case of guest

    if user.is_admin?
      can :manage, :all
    end
  end
end
```

**app/models/user.rb**

```
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :role_assignment, dependent: :destroy
  has_one :role, through: :role_assignment

  validates_presence_of :role, message: "must be selected"

  include RoleMethods

end
```

**app/models/concerns/role_methods.rb**

```
module RoleMethods
  extend ActiveSupport::Concern

  def has_role?(role_sym)
    return false unless role.present?
    role.name.to_sym == role_sym
  end

  def has_no_role?
    role.blank?
  end

  def is_admin?
    has_role?(:admin)
  end
end
```

**app/controllers/users_controller.rb**

```
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  # DELETE /users/:id(.:format)
  def destroy
    @user.destroy

    if @user.destroyed?
      flash.now[:notice] = "Successfully removed user #{@user.display_name}"
    else
      flash.now[:alert] = "#{@user.display_name} was not successfully removed"
    end

    redirect_to users_path, flash: flash.to_hash
  end
end
```

**spec/controllers/users_controller_spec.rb**

```
require 'rails_helper'

RSpec.describe UsersController, type: :controller do
  let!(:current_user) { create(:admin) }

  before do
    sign_in(current_user)
  end

  after do
    sign_out(current_user)
  end

  context "DELETE #destroy" do
    let!(:user) { create(:user) }

    let!(:params) { {}.merge(id: user.id) }

    context "inexistent user" do
      before do
        params.merge!(id: -1)
      end

      it "redirects the user to users listing page with an error message" do
        delete :destroy, params
        expect(response).to redirect_to(users_path)
        expect(flash[:alert]).to be_present
      end
    end
  end
end
```

The rspec example fails with `ActiveRecord::RecordNotFound` error:

```
UsersController
  DELETE #destroy
    inexistent user
      redirects the user to users listing page with an error message (FAILED - 1)

Failures:

  1) UsersController DELETE #destroy inexistent user redirects the user to users listing page with an error message
     Failure/Error: delete :destroy, params
     ActiveRecord::RecordNotFound:
       Couldn't find User with 'id'=-1
     # ~/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/core.rb:154:in `find'
     # ~/.rvm/gems/ruby-2.2.1/gems/cancancan-1.10.1/lib/cancan/model_adapters/abstract_adapter.rb:20:in `find'
     # ~/.rvm/gems/ruby-2.2.1/gems/cancancan-1.10.1/lib/cancan/controller_resource.rb:116:in `find_resource'
     # ~/.rvm/gems/ruby-2.2.1/gems/cancancan-1.10.1/lib/cancan/controller_resource.rb:68:in `load_resource_instance'
     # ~/.rvm/gems/ruby-2.2.1/gems/cancancan-1.10.1/lib/cancan/controller_resource.rb:32:in `load_resource'
     # ~/.rvm/gems/ruby-2.2.1/gems/cancancan-1.10.1/lib/cancan/controller_resource.rb:25:in `load_and_authorize_resource'
     # ~/.rvm/gems/ruby-2.2.1/gems/cancancan-1.10.1/lib/cancan/controller_resource.rb:10:in `block in add_before_filter'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:443:in `instance_exec'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:443:in `block in make_lambda'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:163:in `call'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:163:in `block in halting'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `call'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `block in halting'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `call'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `block in halting'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
     # ~/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:19:in `process_action'
     # ~/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/rescue.rb:29:in `process_action'
     # ~/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `block in instrument'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `instrument'
     # ~/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
     # ~/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
     # ~/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
     # ~/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/abstract_controller/base.rb:137:in `process'
     # ~/.rvm/gems/ruby-2.2.1/gems/actionview-4.2.0/lib/action_view/rendering.rb:30:in `process'
     # ~/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/test_case.rb:629:in `process'
     # ~/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/test_case.rb:65:in `process'
     # ~/.rvm/gems/ruby-2.2.1/gems/devise-3.4.1/lib/devise/test_helpers.rb:19:in `block in process'
     # ~/.rvm/gems/ruby-2.2.1/gems/devise-3.4.1/lib/devise/test_helpers.rb:72:in `catch'
     # ~/.rvm/gems/ruby-2.2.1/gems/devise-3.4.1/lib/devise/test_helpers.rb:72:in `_catch_warden'
     # ~/.rvm/gems/ruby-2.2.1/gems/devise-3.4.1/lib/devise/test_helpers.rb:19:in `process'
     # ~/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/test_case.rb:529:in `delete'
     # ./spec/controllers/users_controller_spec.rb:298:in `block (4 levels) in <top (required)>'
     # ./spec/rails_helper.rb:59:in `block (3 levels) in <top (required)>'
     # ~/.rvm/gems/ruby-2.2.1/gems/database_cleaner-1.4.1/lib/database_cleaner/generic/base.rb:15:in `cleaning'
     # ~/.rvm/gems/ruby-2.2.1/gems/database_cleaner-1.4.1/lib/database_cleaner/base.rb:92:in `cleaning'
     # ~/.rvm/gems/ruby-2.2.1/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # ~/.rvm/gems/ruby-2.2.1/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:87:in `call'
     # ~/.rvm/gems/ruby-2.2.1/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/rails_helper.rb:58:in `block (2 levels) in <top (required)>'

Finished in 1.03 seconds (files took 1.71 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/controllers/users_controller_spec.rb:297 # UsersController DELETE #destroy inexistent user redirects the user to users listing page with an error message

```

I tried using `find_by` option on `load_and_authorize_resource` using a full find method name in following manner ( references: [here](https://github.com/CanCanCommunity/cancancan/blob/develop/spec/cancan/controller_resource_spec.rb#L509) and [here](https://github.com/ryanb/cancan/issues/43#issuecomment-14021265)) :

`load_and_authorize_resource find_by: :find_by_id`

however that failed the spec with following error:

```
UsersController
  DELETE #destroy
    inexistent user

  An error occurred in an `around(:example)` hook
    PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block

    occurred at ~/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:215:in `exec'

      redirects the user to users listing page with an error message (FAILED - 1)

Failures:

  1) UsersController DELETE #destroy inexistent user redirects the user to users listing page with an error message
     Failure/Error: delete :destroy, params
     ActiveRecord::StatementInvalid:
       PG::UndefinedColumn: ERROR:  column users.find_by_id does not exist
       LINE 1: SELECT  "users".* FROM "users" WHERE "users"."find_by_id" = ...
                                                    ^
       : SELECT  "users".* FROM "users" WHERE "users"."find_by_id" = '-1' LIMIT 1
     # ~/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
     # ~/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
     # ~/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # ~/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:460:in `log'
     # ~/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
     # ~/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
     # ~/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
     # ~/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:336:in `select'
     # ~/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
     # ~/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
     # ~/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/querying.rb:39:in `find_by_sql'
     # ~/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/relation.rb:638:in `exec_queries'
     # ~/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/relation.rb:514:in `load'
     # ~/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/relation.rb:243:in `to_a'
     # ~/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/relation/finder_methods.rb:487:in `find_take'
     # ~/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/relation/finder_methods.rb:105:in `take'
     # ~/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/relation/finder_methods.rb:84:in `find_by'
     # ~/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/querying.rb:7:in `find_by'
     # ~/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/core.rb:172:in `find_by'
     # ~/.rvm/gems/ruby-2.2.1/gems/cancancan-1.10.1/lib/cancan/controller_resource.rb:111:in `find_resource'
     # ~/.rvm/gems/ruby-2.2.1/gems/cancancan-1.10.1/lib/cancan/controller_resource.rb:68:in `load_resource_instance'
     # ~/.rvm/gems/ruby-2.2.1/gems/cancancan-1.10.1/lib/cancan/controller_resource.rb:32:in `load_resource'
     # ~/.rvm/gems/ruby-2.2.1/gems/cancancan-1.10.1/lib/cancan/controller_resource.rb:25:in `load_and_authorize_resource'
     # ~/.rvm/gems/ruby-2.2.1/gems/cancancan-1.10.1/lib/cancan/controller_resource.rb:10:in `block in add_before_filter'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:443:in `instance_exec'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:443:in `block in make_lambda'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:163:in `call'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:163:in `block in halting'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `call'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `block in halting'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `call'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `block in halting'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `call'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
     # ~/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:19:in `process_action'
     # ~/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/rescue.rb:29:in `process_action'
     # ~/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `block in instrument'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
     # ~/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `instrument'
     # ~/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
     # ~/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
     # ~/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.0/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
     # ~/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/abstract_controller/base.rb:137:in `process'
     # ~/.rvm/gems/ruby-2.2.1/gems/actionview-4.2.0/lib/action_view/rendering.rb:30:in `process'
     # ~/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/test_case.rb:629:in `process'
     # ~/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/test_case.rb:65:in `process'
     # ~/.rvm/gems/ruby-2.2.1/gems/devise-3.4.1/lib/devise/test_helpers.rb:19:in `block in process'
     # ~/.rvm/gems/ruby-2.2.1/gems/devise-3.4.1/lib/devise/test_helpers.rb:72:in `catch'
     # ~/.rvm/gems/ruby-2.2.1/gems/devise-3.4.1/lib/devise/test_helpers.rb:72:in `_catch_warden'
     # ~/.rvm/gems/ruby-2.2.1/gems/devise-3.4.1/lib/devise/test_helpers.rb:19:in `process'
     # ~/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_controller/test_case.rb:529:in `delete'
     # ./spec/controllers/users_controller_spec.rb:298:in `block (4 levels) in <top (required)>'
     # ./spec/rails_helper.rb:59:in `block (3 levels) in <top (required)>'
     # ~/.rvm/gems/ruby-2.2.1/gems/database_cleaner-1.4.1/lib/database_cleaner/generic/base.rb:15:in `cleaning'
     # ~/.rvm/gems/ruby-2.2.1/gems/database_cleaner-1.4.1/lib/database_cleaner/base.rb:92:in `cleaning'
     # ~/.rvm/gems/ruby-2.2.1/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # ~/.rvm/gems/ruby-2.2.1/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:87:in `call'
     # ~/.rvm/gems/ruby-2.2.1/gems/database_cleaner-1.4.1/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/rails_helper.rb:58:in `block (2 levels) in <top (required)>'

```

Looking at the source code https://github.com/CanCanCommunity/cancancan/blob/master/lib/cancan/controller_resource.rb#L111 it seems like the `else` branch, in source code-snippet shown below, can never be reached because the `elsif` clause gets evaluated to `true` in my case:

```
 elsif resource_base.respond_to? "find_by"
       resource_base.send("find_by", { @options[:find_by].to_sym => id_param })
 else
      resource_base.send(@options[:find_by], id_param)
 end
```

It seems this is because of Rails 4 introduction of `find_by` and `find_by!` methods. 

Thanks,
Jiggneshh

**Comment by lstone** [comment]
I too have run into this issue. +1

**Comment by abhishekbose87** [comment]
@Senjai Hi, I found that the https://github.com/CanCanCommunity/cancancan/commit/4a5700c07e10b9144629f1ae63e0feb195204472 was added at a point of time when rails did not support find_by method. So I rearranged the order of the "if else" conditions in the below manner
```
if resource_base.respond_to? "find_by_#{@options[:find_by]}!"
  resource_base.send("find_by_#{@options[:find_by]}!", id_param)
elsif resource_base.respond_to? @options[:find_by]
  resource_base.send(@options[:find_by], id_param)
else
  resource_base.send("find_by", { @options[:find_by].to_sym => id_param })
end
```
This does make all the current specs pass, and prevents the "PG::UndefinedColumn: ERROR:  column users.find_by_id does not exist" from happening. Can you please tell me whether this will serve our purpose or I am missing something.
