### ISSUE TITLE
Rails 4+ API 'CanCan' not found

### ISSUE THREAD

**Issue by cheeyeo** [CanCanCommunity/cancancan#254]
Hi

I'm developing a Rails API as an engine which sits within a bigger Rails app and have started integrating 'cancancan' within the engine only. When I load the engine up, it keeps failing over with 'Api::CanCan' not found errors? Even with a simple require and also namespacing the ability class did not help.

Is this a known issue or can the gem only works in a standalone application?

I tried debugging the source code but to no avail. Any pointers will be most grateful.

Thank you!

**Comment by cheeyeo** [comment]
The error backtrace

```
ActionController::RoutingError - uninitialized constant ApiApplicationController::CanCan:
  actionpack (4.0.12) lib/action_dispatch/routing/route_set.rb:71:in `rescue in controller'
  actionpack (4.0.12) lib/action_dispatch/routing/route_set.rb:66:in `controller'
  actionpack (4.0.12) lib/action_dispatch/routing/route_set.rb:46:in `call'
  actionpack (4.0.12) lib/action_dispatch/journey/router.rb:71:in `block in call'
  actionpack (4.0.12) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.0.12) lib/action_dispatch/routing/route_set.rb:676:in `call'
  railties (4.0.12) lib/rails/engine.rb:511:in `call'
  railties (4.0.12) lib/rails/railtie/configurable.rb:30:in `method_missing'
  actionpack (4.0.12) lib/action_dispatch/journey/router.rb:71:in `block in call'
  actionpack (4.0.12) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.0.12) lib/action_dispatch/routing/route_set.rb:676:in `call'
  rack (1.5.5) lib/rack/etag.rb:23:in `call'
  rack (1.5.5) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.5) lib/rack/head.rb:11:in `call'
  actionpack (4.0.12) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.0.12) lib/action_dispatch/middleware/flash.rb:241:in `call'
  rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.0.12) lib/action_dispatch/middleware/cookies.rb:486:in `call'
  activerecord (4.0.12) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.0.12) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
  actionpack (4.0.12) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.0.12) lib/active_support/callbacks.rb:373:in `_run__802203667754961445__call__callbacks'
  activesupport (4.0.12) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.12) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.0.12) lib/action_dispatch/middleware/reloader.rb:64:in `call'
  actionpack (4.0.12) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:56:in `call'
  airbrake (3.1.14) lib/airbrake/rails/middleware.rb:13:in `call'
  actionpack (4.0.12) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.0.12) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.0.12) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.0.12) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.0.12) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.0.12) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.0.12) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.0.12) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.0.3) lib/quiet_assets.rb:23:in `call_with_quiet_assets'
  actionpack (4.0.12) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  activesupport (4.0.12) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.0.12) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
  rack-mini-profiler (0.9.2) lib/mini_profiler/profiler.rb:300:in `call'
  airbrake (3.1.14) lib/airbrake/user_informer.rb:16:in `_call'
  airbrake (3.1.14) lib/airbrake/user_informer.rb:12:in `call'
  rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
  railties (4.0.12) lib/rails/engine.rb:511:in `call'
  railties (4.0.12) lib/rails/application.rb:97:in `call'
  rack (1.5.5) lib/rack/content_length.rb:14:in `call'
  puma (2.8.2) lib/puma/server.rb:490:in `handle_request'
  puma (2.8.2) lib/puma/server.rb:361:in `process_client'
  puma (2.8.2) lib/puma/server.rb:254:in `block in run'
  puma (2.8.2) lib/puma/thread_pool.rb:92:in `block in spawn_thread'
```

Rails version: 4.0.12

**Comment by jmarceli** [comment]
I have similar problem. Did you find any solution?
