### ISSUE TITLE
Can not add ability attribute to original Ability via engine 

### ISSUE THREAD

**Issue by wellsonjain** [CanCanCommunity/cancancan#310]
It worked on 1.12.0, but failed on 1.13
Here is snippet in `ability.rb`

```
def self.register_ability(ability)
  self.abilities.add(ability)
end

def initialize(user)
  if user.admin?
    can :manage, :all
  else
    can :read, :dashboard
  end

  Ability.abilities.each do |klass|
    ability = klass.send(:new, user)
    @rules = rules + ability.send(:rules)
  end
end
```

I create a rails engine, and make custom ability

```
require 'cancan'

module Engine
  class AbilityDecorator
    include CanCan::Ability

    def initialize(user)
      if not user.admin?
        can :manage, Post, user_id: user.id
      end
    end
  end
end

# Registers the defined abilities.
Ability.register_ability(Engine::AbilityDecorator)
```

And it shows 

```
CanCan::AccessDenied (You are not authorized to access this page.):
  cancancan (1.13.1) lib/cancan/ability.rb:219:in `authorize!'
  cancancan (1.13.1) lib/cancan/controller_additions.rb:338:in `authorize!'
  cancancan (1.13.1) lib/cancan/controller_resource.rb:41:in `authorize_resource'
  cancancan (1.13.1) lib/cancan/controller_resource.rb:10:in `block in add_before_filter'
  activesupport (4.2.6) lib/active_support/callbacks.rb:448:in `instance_exec'
  activesupport (4.2.6) lib/active_support/callbacks.rb:448:in `block in make_lambda'
  activesupport (4.2.6) lib/active_support/callbacks.rb:164:in `block in halting'
  activesupport (4.2.6) lib/active_support/callbacks.rb:504:in `block in call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:504:in `each'
  activesupport (4.2.6) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.6) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.6) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.6) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.6) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.6) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.6) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.6) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.6) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.6) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.6) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.6) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.6) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.6) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:817:in `call'
  railties (4.2.6) lib/rails/engine.rb:518:in `call'
  railties (4.2.6) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.6) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.6) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  ...
```

**Comment by Schwad** [comment]
Are you trying to allow dynamic ability generation without having to manually include it all in the source code? If so, this is something I'm trying to look into doing as well, also with an engine hooked into a UI to allow some ability/rulesetting for non-rails-devs.

**Comment by steffenschmidt** [comment]
I have the same issue. I figured out that the rules are defined properly but my model is missing in `@rules_index`. That is the difference between defining the ability in the original ability class and in an engine ability decorator.

Any idea how add the class the `@rules_index`?

**Comment by coorasse** [comment]
I am open for PR to enhance CanCanCan behaviour. Please feel free to submit a PR for that.

**Comment by marciodat** [comment]
Hi everyone! I'm was trying to solve this issue and it seems like I found something that work. I'm rather new using rails so pardon me if it is wrong. I read the cancancan code a lot of times and came with the idea to alter a little the code from @wellsonjain to:

```ruby
  Ability.abilities.each do |klass|
    ability = klass.send(:new, user)
    merge(ability)
    # @rules = rules + ability.send(:rules)
  end
```
The `merge` is defined inside the [Ability module](https://github.com/CanCanCommunity/cancancan/blob/8fc2a2dbefc542749650da6b957335e8075b34a3/lib/cancan/ability.rb).

Could someone please, check if really works?
Thanks
Marcio

**Comment by coorasse** [comment]
Closed because of starvation. 
Please feel free to reopen if this issue is still valid or interested in solving with a PR.
Thank you.
