### ISSUE TITLE
ForbiddenAttributesError, on Create of namespaced models with Strong Params

### ISSUE THREAD

**Issue by develop-test1** [CanCanCommunity/cancancan#353]
Steps to reproduce:
Create namespaced resource:
`Api::V1::Set`
Use strong params  and load and authorize resource in controller:

```
class Api::V1::SetsController < ApplicationController
  load_and_authorize_resource
  def create
    @api_v1_set = Api::V1::Set.new(api_v1_set_params)
    if @api_v1_set.save
      render :show, status: :created, location: @api_v1_set
    else
      render json: @api_v1_set.errors, status: :unprocessable_entity
    end
  end
  private
  def api_v1_set_params
    params.require(:api_v1_set).permit(:title)
  end
```

Try to create Set and following error occurs:

```
ActiveModel::ForbiddenAttributesError (ActiveModel::ForbiddenAttributesError):
activemodel (5.0.0.rc1) lib/active_model/forbidden_attributes_protection.rb:21:in `sanitize_for_mass_assignment'
activemodel (5.0.0.rc1) lib/active_model/attribute_assignment.rb:33:in `assign_attributes'
activerecord (5.0.0.rc1) lib/active_record/core.rb:319:in `initialize'
activerecord (5.0.0.rc1) lib/active_record/inheritance.rb:65:in `new'
activerecord (5.0.0.rc1) lib/active_record/inheritance.rb:65:in `new'
cancancan (1.15.0) lib/cancan/controller_resource.rb:88:in `build_resource'
cancancan (1.15.0) lib/cancan/controller_resource.rb:69:in `load_resource_instance'
cancancan (1.15.0) lib/cancan/controller_resource.rb:40:in `load_resource'
cancancan (1.15.0) lib/cancan/controller_resource.rb:33:in `load_and_authorize_resource'
cancancan (1.15.0) lib/cancan/controller_resource.rb:10:in `block in add_before_action'
activesupport (5.0.0.rc1) lib/active_support/callbacks.rb:398:in `instance_exec'
activesupport (5.0.0.rc1) lib/active_support/callbacks.rb:398:in `block in make_lambda'
activesupport (5.0.0.rc1) lib/active_support/callbacks.rb:169:in `call'
activesupport (5.0.0.rc1) lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
actionpack (5.0.0.rc1) lib/abstract_controller/callbacks.rb:12:in `call'
actionpack (5.0.0.rc1) lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
activesupport (5.0.0.rc1) lib/active_support/callbacks.rb:170:in `call'
activesupport (5.0.0.rc1) lib/active_support/callbacks.rb:170:in `block in halting'
activesupport (5.0.0.rc1) lib/active_support/callbacks.rb:454:in `call'
activesupport (5.0.0.rc1) lib/active_support/callbacks.rb:454:in `block in call'
```

If I replace:
`api_v1_set_params`
with:
`set_params`
it works.

However this is against Rails convention that this ignores model namespace. 
I think CanCanCan should properly recognize model namespace.
Is this desired behavior?

**Comment by develop-test1** [comment]
Also wiki suggests https://github.com/CanCanCommunity/cancancan/wiki/Strong-Parameters that when 

> When Model and Controller names differ

 class param can be added:
`load_and_authorize_resource class: 'Set'`
and in fact this resolves above error, however this is not the case here since Model and Controller names do not differ, they are the same..

**Comment by develop-test1** [comment]
For anyone experiencing following problem, I've created temporary workaround in the form of the wrapper module that works for namespaced models:

```
module Api::V1::ApplicationHelper
  extend ActiveSupport::Concern
  included do
    # Fixes CanCanCan issue https://github.com/CanCanCommunity/cancancan/issues/353
    # where namespaced controllers with strong params are raising ForbbidenAttributesError
    # This gets base model name from namespaced controller and passes it as class param:
    # i.e for Api::V1::SetsController it calls:
    # load_and_authorize_resource, class: 'Set'
    def self.load_and_authorize_resource_with_namespace(options = {})
      # Get Model name without namespace
      model_name_without_namespace = { class: controller_name.classify }
      # Add option params if they exist
      params = model_name_without_namespace.merge(options) if options
      load_and_authorize_resource params
    end
  end
end
```

Then you can use `load_and_authorize_resource_with_namespace` within your controller.

**Comment by duffyjp** [comment]
I ran into this same issue, and worked around it by specifying the instance_name I wanted, and then using the [suggested](https://github.com/CanCanCommunity/cancancan/wiki/Strong-Parameters) generic `resource_params` as my method name.

```ruby
class Answer::SetsController < ApplicationController
  load_and_authorize_resource instance_name: :answer_set
  ...
  private
    def resource_params
      params.require(:answer_set).permit( ... )
    end
```

**Comment by stephenamsel** [comment]
My current workaround is just to rename the permission-function, for example from cms_policies_params to policy_params for Cms::Policies.

**Comment by coorasse** [comment]
I think CanCanCan provides already functionalities for those cases. If you think we need to improve the gem with a better names finding when namespaced please open a PR. I am willing to accept it 👍
