### ISSUE TITLE
Method reference error

### ISSUE THREAD

**Issue by wojw5** [CanCanCommunity/cancancan#582]
### Steps to reproduce
Define ability with method reference instead of block.
Example:
```ruby
can :read, Book, &:public?
```

Gist to reproduce:
https://gist.github.com/wojw5/d0f73e6457a8bbb1a976a07a991a5e93

### Expected behavior
Error is not thrown,  ability is checked

### Actual behavior
method `CanCan::ConditionsMatcher#matches_block_conditions` consumes two arguments (`subject`, `*extra_args`), but it is called in with `CanCan::ConditionsMatcher#matches_conditions?` with three (`subject`, `attribute`, `*extra_args`).
It makes `extra_args` to be `[nil]` which is tried to be passed to method reference proc.
```
1) Error:
BugTest#test_bug:
ArgumentError: wrong number of arguments (given 1, expected 0)
    main.rb:25:in `public?'
    /Users/wojtek/.rvm/gems/ruby-2.5.5@cancancan/gems/cancancan-3.0.0/lib/cancan/conditions_matcher.rb:24:in `matches_block_conditions'
    /Users/wojtek/.rvm/gems/ruby-2.5.5@cancancan/gems/cancancan-3.0.0/lib/cancan/conditions_matcher.rb:8:in `matches_conditions?'
    /Users/wojtek/.rvm/gems/ruby-2.5.5@cancancan/gems/cancancan-3.0.0/lib/cancan/ability.rb:77:in `block (2 levels) in can?'
    /Users/wojtek/.rvm/gems/ruby-2.5.5@cancancan/gems/cancancan-3.0.0/lib/cancan/ability.rb:76:in `each'
    /Users/wojtek/.rvm/gems/ruby-2.5.5@cancancan/gems/cancancan-3.0.0/lib/cancan/ability.rb:76:in `detect'
    /Users/wojtek/.rvm/gems/ruby-2.5.5@cancancan/gems/cancancan-3.0.0/lib/cancan/ability.rb:76:in `block in can?'
    /Users/wojtek/.rvm/gems/ruby-2.5.5@cancancan/gems/cancancan-3.0.0/lib/cancan/ability.rb:79:in `each'
    /Users/wojtek/.rvm/gems/ruby-2.5.5@cancancan/gems/cancancan-3.0.0/lib/cancan/ability.rb:79:in `each'
    /Users/wojtek/.rvm/gems/ruby-2.5.5@cancancan/gems/cancancan-3.0.0/lib/cancan/ability.rb:79:in `each'
    /Users/wojtek/.rvm/gems/ruby-2.5.5@cancancan/gems/cancancan-3.0.0/lib/cancan/ability.rb:79:in `each'
    /Users/wojtek/.rvm/gems/ruby-2.5.5@cancancan/gems/cancancan-3.0.0/lib/cancan/ability.rb:79:in `first'
    /Users/wojtek/.rvm/gems/ruby-2.5.5@cancancan/gems/cancancan-3.0.0/lib/cancan/ability.rb:79:in `can?'
    main.rb:47:in `test_bug'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

### System configuration
**Rails version**:
4.2.11 (not related)
**Ruby version**:
2.5.5 (not related)
**CanCanCan version**
3.0.0

**Comment by coorasse** [comment]
Yes, I confirm that this was working on cancancan 2.3.0
