### ISSUE TITLE
[BUG] Application crashes on Ruby 3

### ISSUE THREAD

**Issue by mike927** [CanCanCommunity/cancancan#770]
### Steps to reproduce
Any controller: 
```ruby
class UsersController < ApiController
    authorize_resource
end
```

From Ruby 3 passing hash directly to the method as variable is no longer valid. In the following method:
```ruby
module CanCan
  module Ability
    def unauthorized_message(action, subject)
      keys = unauthorized_message_keys(action, subject)
      variables = { action: action.to_s }
      variables[:subject] = (subject.class == Class ? subject : subject.class).to_s.underscore.humanize.downcase
      message = I18n.translate(nil, variables.merge(scope: :unauthorized, default: keys + ['']))
      message.blank? ? nil : message
    end
  end
end
```
you pass hash without now required `double splat operator (**)` what breaks in:

`.rvm/gems/ruby-3.0.1/gems/i18n-1.10.0/lib/i18n.rb`
```ruby
def translate(key = nil, throw: false, raise: false, locale: nil, **options)
```

### Steps to fix:
Prefix `variables.merge(scope: :unauthorized, default: keys + [''])` with double splat operator:
```ruby
module CanCan
  module Ability
    def unauthorized_message(action, subject)
      keys = unauthorized_message_keys(action, subject)
      variables = { action: action.to_s }
      variables[:subject] = (subject.class == Class ? subject : subject.class).to_s.underscore.humanize.downcase
      message = I18n.translate(nil, **variables.merge(scope: :unauthorized, default: keys + ['']))
      message.blank? ? nil : message
    end
  end
end
```

Source: https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

### Expected behavior
It should throw expected `CanCan::AccessDenied` exception.

### Actual behavior
```
 "status": 500,
    "error": "Internal Server Error",
    "exception": "#<ArgumentError: wrong number of arguments (given 2, expected 0..1)>",
    "traces": {
        "Application Trace": [],
        "Framework Trace": [
            {
                "exception_object_id": 24500,
                "id": 0,
                "trace": "i18n (1.10.0) lib/i18n.rb:210:in `translate'"
            },
            {
                "exception_object_id": 24500,
                "id": 1,
                "trace": "cancancan (1.17.0) lib/cancan/ability.rb:226:in `unauthorized_message'"
            },
```

### System configuration
**Rails version**: 7.0.2.2

**Ruby version**: 3.0.1

**CanCanCan version**: 1.17.0

**Comment by shnikola** [comment]
@mike927, I had the same issue, because I had

`gem 'cancancan', '~> 1.10'`

in my Gemfile. Cancan is now on version 3.3.0, which works fine with Ruby 3.0.

**Comment by coorasse** [comment]
Yes, cancancan is tested and should be working with ruby 3.0.1 without issues.

**Comment by shadydealer** [comment]
For anybody else that runs into this issue, this is actually fixed in 3.1.0, not 3.0.1
